language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master

env:
  global:
    secure: "Piqw3uPTC9MevxycWz8KNNyItykYq3Yvt9o0in1QpxI9hr8NBS2JJtFtEdOpQi01VaBwWmSLh7lmBBnQDBcuS3tYQjlEIB0a/lfbPxLj6w1B7slJkv//08kXs3sutegMuhv0pXqiN2155G0V5N9dx5VtqKoD/znp6IjF7MmzX/Q="

install:
  - npm install -g grunt-cli bower
  - npm install
  - bower install

script:
  - grunt package
  - grunt test

after_success:
  - grunt gh-pages