language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master

env:
  global:
    secure: "CVdgvBm1XI2itnZQGakTnq6rmwOfYv8j9E7MKy5dF0gQ46kRVNmoMKSQqaRvIVsnXbv+BVrL6Qa+1BGJUd74n2RJOad5c0ikfxRR7Mt9/x3MyF88ru4dL85qWx4bU6kyq85FkF/7hUtLdaOk/iL1HdqBk842Kx45zdhXD9xL7Z4="

install:
  - npm install -g grunt-cli bower
  - npm install
  - bower install

script:
  - grunt package
  - grunt test

after_success:
  - grunt gh-pages